webapp/profile/views.py
import json
import re 

from webapp.user.models import User, UserData
from webapp.model import db
from webapp.user.forms import TrackForm

from flask_login import current_user, login_required
from flask import Blueprint, render_template, flash, redirect, url_for, request


blueprint = Blueprint('profile', __name__, url_prefix='/profile')

@blueprint.route("/account")
@login_required
def account():
    title = "Account"
    track_count = UserData.query.filter(UserData.user_id == current_user.id).count()   
    return render_template('profile/account.html', page_title=title, name=current_user.username, track_count=track_count, role=current_user.role, email=current_user.email)

@blueprint.route("/mylist")
@login_required
def mylist():
    title = "My List"
    data = UserData.query.filter(UserData.user_id == current_user.id).all()
    return render_template('/profile/mylist.html', page_title=title, data=data)

@blueprint.route('/newtrack')
@login_required
def newtrack():
    title = "Create track"
    track_form = TrackForm(user_id=current_user.id)
    return render_template('/profile/newtrack.html', page_title=title,  track_form=track_form)

@blueprint.route('/get_notes', methods=['GET', 'POST'])
def get_notes():
    name = request.form['name']
    pattern = r'<td>(.*?)</td>'     
    match = re.findall(pattern, name)
    list_view = match[::2]
    dict_view = str(dict(zip(range(1, (len(list_view)+1)), list_view)))
    table_view = json.dumps({'view': list_view, 'data': dict_view}) 
    print(table_view)
    return table_view

@blueprint.route('add_track', methods=['POST'])
def add_track():
    form = TrackForm()
    if form.validate_on_submit():
            track = UserData(artist=form.artist.data, title=form.title.data, comment=form.comment.data, notes=form.notes.data, user_id=current_user.id)
            db.session.add(track)
            db.session.commit()
            flash('Successfully added')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Mistake in field "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))        
    return redirect(request.referrer)   

webapp/user/views.py
from webapp.user.models import User
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.model import db
from flask_login import current_user, login_user, logout_user
from flask import Blueprint, render_template, flash, redirect, url_for

blueprint = Blueprint('users', __name__, url_prefix='/users')
 
@blueprint.route("/login")
def login():
    title = "Log in"
    login_form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    return render_template('/user/login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Welcome!')
            return redirect(url_for('profile.account'))

    flash('Incorrect usrname or password')
    return redirect(url_for('users.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

@blueprint.route('/signup')
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    title = "Sign Up"
    form = RegistrationForm()
    return render_template('/user/signup.html', page_title=title, form=form)  

@blueprint.route('process_reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Successful registration')
        return redirect(url_for('users.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Mistake in field "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('users.signup'))

         

webapp/templates/profile/account.html
{% extends "base.html" %}

{% block content %}

{% include 'profile/message.html' %}
  <!-- Page Content -->
  <div class="container">
<!-- Page Heading/Breadcrumbs -->
{% include 'profile/heading.html' %} 
<!-- Side Menu -->
{% include 'profile/sidebar.html' %}
    <!-- Content Row -->
 
      <!-- Content Column -->
      <div class="col-lg-9 mb-4">
        <h2>Overview</h2>
        <p>Name: {{ name }}<br>
          Email: {{ email }}<br>
          Tracks: {{ track_count }}</p>
      </div>
    </div>
  </div>
   
  <!-- /.container -->

  {% endblock %}

webapp/templates/profile/heading.html
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Profile
        <small>{{ role }}</small>
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/">Home</a>
        </li>
      </ol>
      <div class="row">

webapp/templates/profile/message.html
  {% with messages = get_flashed_messages() %}
  {% if messages %}
  <div class="alert alert-warning" role="alert">
      {% for message in messages %}
          {{ message }}<br>
      {% endfor %}
  </div>
  {% endif %}
  {% endwith %}

 
  

webapp/templates/profile/mylist.html
{% extends 'base.html' %}

{% block content %}

{% include 'profile/message.html' %}

  <!-- Page Content -->
  <div class="container">
<!-- Page Heading/Breadcrumbs -->     
{% include 'profile/heading.html' %} 
<!-- Side Menu -->
{% include 'profile/sidebar.html' %}    

<div class="col-lg-9 mb-4">
    <h2>My Tracks</h2>
   
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Artist</th>
                    <th>Comment</th>
                    <th>URL</th>
                    <th>Date</th>
               </tr>
            </thead>
            <tbody>
                {% for name in data %}
            <tr>
                <td>{{ name.title }}</td>
                <td>{{ name.artist }}</td>
                <td>{{ name.comment }}</td>
                <td><a href="/">Go</a></td>
                <td>{{ name.created }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
 </div>
 </div>
 </div>
 </div>   

{% endblock %}

webapp/templates/profile/newtrack.html
{% extends "base.html" %}

{% block content %}

{% include 'profile/message.html' %}

<!-- Page Content -->
<div class="container">
<!-- Page Heading/Breadcrumbs -->
{% include 'profile/heading.html' %} 


<!-- Content Row -->
{% include 'profile/sidebar.html' %}
  <!-- Content Column -->
  <div class="col-lg-9 mb-4">
    <h2>New track</h2>
<form action="{{ url_for('profile.add_track') }}" method="POST">
  {{ track_form.hidden_tag() }}
<div class="form form-group">
  {{ track_form.artist.label }}
  {{ track_form.artist() }}<br>
  {{ track_form.title.label }}
  {{ track_form.title() }}<br>
  {{ track_form.comment.label }}
  {{ track_form.comment() }}<br>
 

<!-- Modal Results <div id="len">-->  
<table id="view"><tr></tr></table>
<!-- Modal Call -->
  <a data-toggle="modal" href="#myModal" data-target="#myModal" data-backdrop="static" onclick=hide>Add Notes</a>
 </div>
   {{ track_form.submit() }}
</form>

  <!-- Modal HTML -->
  <div id="myModal" class="modal fade" role="dialog" name="modal">
      <div class="modal-dialog"> 
          <div class="modal-content">
            <div class="modal-header">
              <h3>Add Notes</h3>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <link href="/static/css/font.css" rel="stylesheet">
              <script src="/static/js/music.js"></script>

                Enter notes:<br>
                <textarea id="rawnotes" name="bt"></textarea>
                <input type="button" value="Add" onClick="btnClick();">
                <form>
                <input type="hidden" name="name" id="hf">
                <div class="table">
                <table id="table" name="table"></table>
                </div>
                </form>
                
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button class="btn btn-primary" onclick="get_notes();">Save changes</button>
            </div>

      </div>
    </div>
  </div>


          </div>
      </div>
  </div>

{% endblock %}

webapp/templates/profile/sidebar.html
      <!-- Sidebar Column -->
      <div class="col-lg-3 mb-4">
        <div class="list-group">
          <a href="{{ url_for('profile.account') }}" class="list-group-item">Profile</a>
            {% if current_user.is_tutor %}
          <a href="/admin/track" class="list-group-item">Tracks</a>
              {% else %}
          <a href="{{ url_for('profile.mylist') }}" class="list-group-item">My List</a>
              {% endif %}
          <a href="{{ url_for('profile.newtrack') }}" class="list-group-item" >New Track</a>
          <a href="printing.html" class="list-group-item">Printing Table</a>
          <a href="{{ url_for('feedback') }}" class="list-group-item">Feedback</a>
          <a href="{{ url_for('users.logout') }}" class="list-group-item">Log Out</a>
        </div>
      </div>
   