webapp/user/models.py
from datetime import datetime
from flask_login import UserMixin
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.model import db

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50), unique=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    @property
    def is_tutor(self):
        return self.role == 'tutor'

    def __repr__(self):
        return '<User {}>'.format(self.username)

class UserData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    artist = db.Column(db.String, nullable=False)
    title = db.Column(db.String, nullable=False)
    comment = db.Column(db.String, nullable=True)
    notes = db.Column(db.String, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )

    user = relationship('User', backref='UserData')

    def __repr__(self):
        #return 'UserData {}'.format(self.id)
        return f'{self.id}, {self.artist}, {self.title}, {self.comment}'

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, PasswordField, SubmitField, HiddenField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me', default=True, render_kw={"class": "form-check-input"})
    submit = SubmitField('Send', render_kw={"class": "btn btn-primary"})


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign up', render_kw={"class": "btn btn-primary"})

    def validate_username(self, username):
        users_count = User.query.filter_by(username=username.data).count()
        if users_count > 0:
            raise ValidationError('Username already exists')

    def validate_email(self, email):
        users_count = User.query.filter_by(email=email.data).count()
        if users_count > 0:
            raise ValidationError('An account with that email already exists')


class TrackForm(FlaskForm):
    user_id = HiddenField('ID', validators=[DataRequired()])
    artist = StringField('Artist', validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired()])
    comment = StringField('Comment', validators=[DataRequired()])
    notes = HiddenField('Notes', validators=[DataRequired()])
    submit = SubmitField('Save', render_kw={"class": "btn btn-primary"})

    def validate_user_id(self, user_id):
        if not User.query.get(user_id.data):
            raise ValidationError('No such user here')

webapp/user/views.py
from webapp.user.models import User
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.model import db
from flask_login import current_user, login_user, logout_user
from flask import Blueprint, render_template, flash, redirect, url_for

blueprint = Blueprint('users', __name__, url_prefix='/users')
 
@blueprint.route("/login")
def login():
    title = "Log in"
    login_form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    return render_template('/user/login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Welcome!')
            return redirect(url_for('profile.account'))

    flash('Incorrect usrname or password')
    return redirect(url_for('users.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

@blueprint.route('/signup')
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    title = "Sign Up"
    form = RegistrationForm()
    return render_template('/user/signup.html', page_title=title, form=form)  

@blueprint.route('process_reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Successful registration')
        return redirect(url_for('users.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Mistake in field "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('users.signup'))

         

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}


  <!-- Page Content -->
  <div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Authentication</h1>
      <small></small>
    </h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="/">Home</a>
      </li>
    </ol>
    <form action="{{ url_for('users.process_login') }}" method="post">
    <p> {{ form.hidden_tag() }}
      <div class="form-group">
          {{ form.username.label }}<br>
          {{ form.username() }}
      </div>
      <div class="form-group">
          {{ form.password.label }}<br>
          {{ form.password() }}
      </div>
     
      <div class="form-group form-chek">
          {{ form.remember_me }}
          {{ form.remember_me.label (class_='form-chek-label') }}
         
      </div>  
        {{ form.submit() }}
        <br>
      </p>    
  </form>
  </div>
  <!-- /.container -->
  
  {% endblock %}

webapp/templates/user/signup.html
{% extends "base.html" %}

{% block content %}

<!-- Page Content -->
<div class="container">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
  
 

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Registration
      <small></small>
    </h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="/">Home</a>
      </li>
      </ol>
  </ol>

  <form action="{{ url_for('users.process_reg') }}" method="post">
  <p> {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label }}<br>
        {{ form.username() }}
    </div>
    <div class="form-group">
      {{ form.email.label }}<br>
      {{ form.email() }}
  </div>
    <div class="form-group">
        {{ form.password.label }}<br>
        {{ form.password() }}
    </div>
    <div class="form-group">
      {{ form.password2.label }}<br>
      {{ form.password2() }}
     </div>
      {{ form.submit() }}
    </p>
</form>
</div>
  <!-- /.container -->

  {% endblock %}